### ISSUE TITLE
Link to coverr video is no longer working

### ISSUE THREAD

**Issue by andrericardo** [wesbos/What-The-Flexbox#10]
https://github.com/wesbos/What-The-Flexbox/blob/d28d2b0547da0d104921d1b88184c765750ee39f/flexbox-form/index.html#L39]

Now a zip file is provided at
https://storage.googleapis.com/coverr-main/zip/Coverr-Lulu.zip

**Comment by thewheat** [comment]
This looks like it can be closed as it was fixed here 😄  https://github.com/wesbos/What-The-Flexbox/pull/12
