### ISSUE TITLE
Issues on Chrome with "FlexBox App Layout"

### ISSUE THREAD

**Issue by pacid** [wesbos/What-The-Flexbox#2]
Hey Wes!

Great tutorial. Thanks! 

Just testing the code used for the last video and it renders not so well. 
"Firefox 49, Ubuntu" on the left: all good
"Chrome Version 36.0.1985.125, Ubuntu" on the right: not so great
and btw checked that also on Windows "Chrome Version 53.0.2785.143 m, Windows" : not so great

![screenshot from 2016-10-09 23-51-57](https://cloud.githubusercontent.com/assets/1618052/19223952/904de2ca-8e7b-11e6-8392-2840f256b0ac.png)

Any idea why?

**Comment by pacid** [comment]
Ah, of course, might be because I didn't run those through autoprefixer.

**Comment by ghost** [comment]
@pacid i fix it :) 

just add this 
`.icon-bar {
    display: flex;
    justify-content: center;
    flex-shrink: 0;
}`

**Comment by naterexw** [comment]
@BorodinDemid can you explain your code?  

flex-shrink is a flex item property, yet you are assigning it to the .icon-bar flex container

**Comment by ghost** [comment]
@naterexw this is just bug most browsers.

When flex items are too big to fit inside their container, those items are instructed (by the flex layout algorithm) to shrink, proportionally, according to their flex-shrink property. But contrary to what many browsers allow, they’re not supposed to shrink indefinitely. They must always be at least as big as their minimum height or width properties declare, and if no minimum height or width properties are set, their minimum size should be the default minimum size of their content.

**Comment by osmaniarb** [comment]
this fixed it:

```
.app-header {
  display: flex;
  flex-shrink: 0;
}
```
